[build]
	command = "gatsby build"
 	publish = "public"

[[plugins]]
  	package = "netlify-plugin-submit-sitemap"

		[plugins.inputs]

		baseUrl = "https://www.matthewtao.com"
		sitemapPath = "/sitemap/sitemap-index.xml"